### ISSUE TITLE
game.yml

### ISSUE THREAD

**Issue by Descent098** [terminal-game-platform/launcher#3]
```game.yml``` is the config file at the root of each game with the following attributes:

```yml
name: "name of game"
version: 1
subtitle: "If the game has a subheading"

```

This can then be cloned using:

```python
from git import Repo
Repo.clone_from(game_url, folder)
```
